version: '3.4'

services:

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "15040:80"
    volumes:
      - poc-seq:/data

  sqlserver:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1533:1433"
    volumes:
      - poc-sqlserver:/var/opt/mssql

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "poc-rabbitmq:/var/lib/rabbitmq"

  issues-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthServiceHttpExternalUrl=http://${POC_EXTERNAL_DNS_NAME_OR_IP}:15010
    ports:
      - "15000:80"
      - "15001:81"

  users-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - AuthServiceHttpExternalUrl=http://${POC_EXTERNAL_DNS_NAME_OR_IP}:15010
    ports:
      - "15005:80"
      - "15006:81"

  auth-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - UserServiceGrpcUrl=http://users-api:81
      - UserServiceHttpUrl=http://users-api
      - AuthServiceHttpExternalUrl=http://${POC_EXTERNAL_DNS_NAME_OR_IP}:15010
      - WebBffAggregatorHttpExternalUrl=http://${POC_EXTERNAL_DNS_NAME_OR_IP}:15015
    ports:
      - "15010:80"

  webbff-aggregator:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - UserServiceGrpcUrl=http://users-api:81
      - UserServiceHttpUrl=http://users-api
      - IssueServiceGrpcUrl=http://issues-api:81
      - IssueServiceHttpUrl=http://issues-api
      - AuthServiceHttpExternalUrl=http://${POC_EXTERNAL_DNS_NAME_OR_IP}:15010
    ports:
      - "15015:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - HealthChecksUI__HealthChecks__0__Name=User Service HTTP Check
      - HealthChecksUI__HealthChecks__0__Uri=http://users-api/hc
      - HealthChecksUI__HealthChecks__1__Name=Auth Service Check
      - HealthChecksUI__HealthChecks__1__Uri=http://auth-api/hc
      - HealthChecksUI__HealthChecks__2__Name=Issue Service HTTP Check
      - HealthChecksUI__HealthChecks__2__Uri=http://issues-api/hc
      - HealthChecksUI__HealthChecks__3__Name=Web Bff HTTP Check
      - HealthChecksUI__HealthChecks__3__Uri=http://webbff-aggregator/hc
    ports:
      - "5341:80"

volumes:

  poc-sqlserver:
    external: false

  poc-seq:
    external: false

  poc-rabbitmq:
    external: false