version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  issues-api:
    image: ${DOCKER_REGISTRY-poc}/issues.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Issues/Issues.API/Dockerfile
    depends_on:
      - sqlserver 
      - auth-api
      - rabbitmq

  users-api:
    image: ${DOCKER_REGISTRY-poc}/users.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Users/Users.API/Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  auth-api:
    image: ${DOCKER_REGISTRY-poc}/auth.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile
    depends_on:
      - users-api

  webbff-aggregator:
    image: ${DOCKER_REGISTRY-poc}/webbff.aggregator:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Gateways/WebBff/WebBff.Aggregator/Dockerfile
    depends_on:
      - users-api
      - auth-api
      - issues-api

  webstatus:
    image: ${DOCKER_REGISTRY-poc}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile
    depends_on:
      - auth-api
      - webbff-aggregator
      - users-api
      - issues-api